runtime: nodejs20

# Basic app configuration
service: oracle-service
instance_class: F2

# Environment variables (set these in GCP Console for security)
env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # Don't put secrets here - use Secret Manager instead

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Network settings
network:
  forwarded_ports:
    - 8080

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Resource limits
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Files to skip during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules$
  - ^(.*/)?tests?/.*$
  - ^(.*/)?\.env$